import os
import re
import threading
import time
from tkinter import filedialog
from urllib.parse import quote

import customtkinter as ctk

from .helpers import append_textbox

MIN_VIEW_COUNT = 200_000
AI_KEYWORDS = [
    " ai ",
    "#ai",
    "artificial intelligence",
    "chatgpt",
    "midjourney",
    "stable diffusion",
    "runway",
    "sora",
    "kling",
    "veo",
    "pixverse",
    "pika",
    "generated by ai",
    "ai generated",
    "ai video",
    "ai voice",
    "ai cover",
    "ai animation",
    "ai art",
    "deepfake",
    "synthetic voice",
]


class SearchDownloadTab:
    def __init__(self, app, parent, downloader):
        self.app = app
        self.parent = parent
        self.downloader = downloader
        self.output_dir = os.getcwd()
        self.tiktok_profile_dir = os.path.join(os.getcwd(), "tiktok_browser_profile")

        self._build_ui()
        self.append_log(f"Thu muc luu mac dinh: {self.output_dir}")

    def _build_ui(self):
        title = ctk.CTkLabel(
            self.parent,
            text="Tim chu de va tai video TikTok",
            font=ctk.CTkFont(size=18, weight="bold"),
        )
        title.pack(pady=(16, 10))

        note = ctk.CTkLabel(
            self.parent,
            text="Nhap chu de can tim, so video can tai va view toi thieu. Tool se mo search TikTok, cuon lay them ket qua neu can, loc theo view roi tai ve.",
            wraplength=820,
            justify="left",
        )
        note.pack(padx=20, pady=(0, 10), anchor="w")

        keyword_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        keyword_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(keyword_frame, text="Chu de", width=120, anchor="w").pack(side="left")
        self.keyword_entry = ctk.CTkEntry(
            keyword_frame,
            width=620,
            placeholder_text="Vi du: dog play with ball",
        )
        self.keyword_entry.pack(side="left", padx=(0, 10), fill="x", expand=True)

        count_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        count_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(count_frame, text="So video", width=120, anchor="w").pack(side="left")
        self.limit_entry = ctk.CTkEntry(count_frame, width=120)
        self.limit_entry.pack(side="left")
        self.limit_entry.insert(0, "10")

        min_view_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        min_view_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(min_view_frame, text="Min view", width=120, anchor="w").pack(side="left")
        self.min_view_entry = ctk.CTkEntry(min_view_frame, width=120)
        self.min_view_entry.pack(side="left")
        self.min_view_entry.insert(0, str(MIN_VIEW_COUNT))

        max_duration_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        max_duration_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(max_duration_frame, text="Max giay", width=120, anchor="w").pack(side="left")
        self.max_duration_entry = ctk.CTkEntry(max_duration_frame, width=120)
        self.max_duration_entry.pack(side="left")
        self.max_duration_entry.insert(0, "0")
        ctk.CTkLabel(
            max_duration_frame, text="Chi tai video ngan hon so giay nay (0 = khong gioi han)", anchor="w"
        ).pack(side="left", padx=(10, 0))

        output_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        output_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(output_frame, text="Thu muc dich", width=120, anchor="w").pack(side="left")
        self.output_entry = ctk.CTkEntry(output_frame, width=620)
        self.output_entry.pack(side="left", padx=(0, 10), fill="x", expand=True)
        self.output_entry.insert(0, self.output_dir)
        ctk.CTkButton(output_frame, text="Chon dich", command=self.choose_output_dir, width=120).pack(side="left")

        ctk.CTkButton(self.parent, text="Tim va tai", command=self.start_search_download, width=180).pack(pady=8)

        self.log_box = ctk.CTkTextbox(self.parent, height=360, width=860)
        self.log_box.pack(padx=20, pady=(10, 20), fill="both", expand=True)

    def append_log(self, text):
        append_textbox(self.app, self.log_box, text)

    def set_entry_value(self, entry, value):
        entry.delete(0, "end")
        entry.insert(0, value)

    def choose_output_dir(self):
        selected = filedialog.askdirectory(initialdir=self.output_dir)
        if selected:
            self.output_dir = selected
            self.set_entry_value(self.output_entry, selected)
            self.append_log(f"Thu muc dich: {selected}")

    def build_search_url(self, keyword):
        encoded_keyword = quote(keyword)
        timestamp = int(time.time() * 1000)
        return f"https://www.tiktok.com/search?q={encoded_keyword}&t={timestamp}"

    def resolve_search_url(self, keyword_or_url):
        return self.build_search_url(keyword_or_url.strip())

    def get_search_label(self, keyword_or_url):
        return keyword_or_url.strip()

    def create_browser_context(self, playwright, headless):
        os.makedirs(self.tiktok_profile_dir, exist_ok=True)
        return playwright.chromium.launch_persistent_context(
            self.tiktok_profile_dir,
            headless=headless,
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/136.0.0.0 Safari/537.36"
            ),
            viewport={"width": 1440, "height": 1600},
            locale="en-US",
        )

    def fetch_search_page(self, keyword_or_url, target_count):
        from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
        from playwright.sync_api import sync_playwright

        url = self.resolve_search_url(keyword_or_url)

        with sync_playwright() as playwright:
            context = self.create_browser_context(playwright, headless=True)
            page = context.new_page()
            page.goto(url, wait_until="domcontentloaded", timeout=60000)

            try:
                page.wait_for_selector('[id^="grid-item-container-"]', timeout=20000)
            except PlaywrightTimeoutError:
                self.append_log("Khong thay grid-item-container, se thu quet link video toan trang.")

            candidate_target = max(target_count * 6, 30)
            previous_count = 0
            stable_rounds = 0
            for _ in range(8):
                page.wait_for_timeout(2000)
                html_text = page.content()
                current_count = len(self.extract_video_links_from_html(html_text, candidate_target))
                if current_count >= candidate_target:
                    break
                if current_count <= previous_count:
                    stable_rounds += 1
                else:
                    stable_rounds = 0
                if stable_rounds >= 2:
                    break
                previous_count = current_count
                page.mouse.wheel(0, 4000)

            page.wait_for_timeout(1500)
            html_text = page.content()
            final_url = page.url
            page_title = page.title()

            context.close()
            return html_text, final_url, page_title

    def page_looks_like_generic_tiktok_shell(self, html_text, page_title):
        title_value = (page_title or "").strip().lower()
        html_lower = (html_text or "").lower()
        return (
            title_value == "tiktok - make your day"
            and "/video/" not in html_lower
            and "find '" not in title_value
        )

    # href co the la URL tuyet doi hoac tuong doi, va co the keo theo query param
    VIDEO_HREF_PATTERN = re.compile(
        r'href="(?:https://www\.tiktok\.com)?(/@[^"/]+/video/\d+)[^"]*"',
        flags=re.IGNORECASE,
    )

    def extract_video_links_from_html(self, html_text, limit):
        container_ids = [f"grid-item-container-{index}" for index in range(0, limit)]

        found_links = []
        seen_links = set()

        def add_link(path):
            video_url = f"https://www.tiktok.com{path}"
            if video_url in seen_links:
                return False
            seen_links.add(video_url)
            found_links.append(video_url)
            return True

        for container_id in container_ids:
            anchor_pattern = re.compile(
                rf'id="{re.escape(container_id)}".{{0,3000}}?href="(?:https://www\.tiktok\.com)?(/@[^"/]+/video/\d+)[^"]*"',
                flags=re.IGNORECASE | re.DOTALL,
            )
            match = anchor_pattern.search(html_text)
            if match:
                add_link(match.group(1))

        if found_links:
            return found_links[:limit]

        for href_match in self.VIDEO_HREF_PATTERN.finditer(html_text):
            add_link(href_match.group(1))
            if len(found_links) >= limit:
                break

        return found_links

    def is_ai_content(self, info):
        combined_parts = [
            info.get("title", ""),
            info.get("description", ""),
            info.get("uploader", ""),
            info.get("channel", ""),
            " ".join(info.get("tags") or []),
        ]
        combined_text = f" {' '.join(part for part in combined_parts if part)} ".lower()
        return any(keyword in combined_text for keyword in AI_KEYWORDS)

    def filter_video_urls_by_views(self, video_urls, min_view_count, target_count, max_duration_seconds=0):
        filtered_urls = []
        for index, video_url in enumerate(video_urls, start=1):
            if index > 1:
                time.sleep(1)  # tikwm free gioi han ~1 request/giay
            try:
                info = self.downloader.get_video_info(video_url)
                _, view_count = self.downloader.extract_title_and_view_count(info)
                if self.is_ai_content(info):
                    self.append_log(f"[{index}] Bo qua vi nghi la noi dung AI | {video_url}")
                    continue
                duration = self.downloader.parse_count_value(info.get("duration"))
                if max_duration_seconds > 0 and duration >= max_duration_seconds:
                    self.append_log(
                        f"[{index}] Bo qua vi dai {duration}s (can < {max_duration_seconds}s) | {video_url}"
                    )
                    continue
                if view_count >= min_view_count:
                    filtered_urls.append((video_url, view_count))
                    self.append_log(
                        f"[{index}] Dat view: {self.downloader.format_view_count(view_count)} | {video_url}"
                    )
                    if len(filtered_urls) >= target_count:
                        break
                else:
                    self.append_log(
                        f"[{index}] Bo qua vi view thap: {self.downloader.format_view_count(view_count)} | {video_url}"
                    )
            except Exception as exc:
                self.append_log(f"[{index}] Khong doc duoc view, bo qua: {video_url} | {exc}")
        return filtered_urls

    def search_and_download(self):
        keyword = self.keyword_entry.get().strip()
        self.output_dir = self.output_entry.get().strip() or self.output_dir

        if not keyword:
            self.append_log("Vui long nhap chu de can tim.")
            return

        try:
            limit = int(self.limit_entry.get().strip() or "6")
        except ValueError:
            self.append_log("So luong video phai la so.")
            return

        try:
            min_view_count = int(self.min_view_entry.get().strip() or str(MIN_VIEW_COUNT))
        except ValueError:
            self.append_log("Min view phai la so.")
            return

        try:
            max_duration_seconds = int(self.max_duration_entry.get().strip() or "0")
        except ValueError:
            self.append_log("Max giay phai la so.")
            return

        if max_duration_seconds < 0:
            self.append_log("Max giay phai >= 0.")
            return

        if limit <= 0:
            self.append_log("So luong video phai lon hon 0.")
            return

        if min_view_count < 0:
            self.append_log("Min view phai >= 0.")
            return

        if not self.output_dir:
            self.append_log("Vui long chon thu muc dich.")
            return

        os.makedirs(self.output_dir, exist_ok=True)

        duration_label = f" | max giay: {max_duration_seconds}" if max_duration_seconds > 0 else ""
        self.append_log(
            f"Dang tim video cho chu de: {self.get_search_label(keyword)} | so luong: {limit} | min view: {min_view_count}{duration_label}"
        )
        try:
            html_text, final_url, page_title = self.fetch_search_page(keyword, limit)
            self.append_log(f"Playwright da mo trang: {final_url}")
            if self.page_looks_like_generic_tiktok_shell(html_text, page_title):
                self.append_log(
                    "TikTok dang tra ve trang chung thay vi ket qua tim kiem. Cookie/session hien tai co kha nang da het hieu luc hoac bi dua vao login gate."
                )
                return
            video_urls = self.extract_video_links_from_html(html_text, max(limit * 6, 30))
        except Exception as exc:
            self.append_log(f"Loi khi lay ket qua tim kiem: {exc}")
            return

        if not video_urls:
            debug_path = os.path.join(os.getcwd(), "tiktok_search_debug.html")
            try:
                with open(debug_path, "w", encoding="utf-8") as debug_file:
                    debug_file.write(html_text)
                self.append_log(f"Da luu HTML trang search vao: {debug_path}")
            except OSError:
                pass
            self.append_log(
                "Khong tim thay link video nao tu trang search TikTok. Kha nang cao TikTok da doi DOM hoac session hien tai khong duoc cap search result."
            )
            return

        filtered_video_urls = self.filter_video_urls_by_views(
            video_urls, min_view_count, limit, max_duration_seconds
        )
        if not filtered_video_urls:
            self.append_log(f"Khong co video nao dat nguong >= {min_view_count} view.")
            return

        if len(filtered_video_urls) < limit:
            self.append_log(
                f"Chi tim duoc {len(filtered_video_urls)}/{limit} video dat nguong >= {min_view_count} view."
            )
        else:
            self.append_log(
                f"Tim thay du {len(filtered_video_urls)} video dat nguong >= {min_view_count} view."
            )
        previous_dir = self.downloader.download_dir
        self.downloader.download_dir = self.output_dir
        self.downloader.set_entry_value(self.downloader.download_dir_entry, self.output_dir)

        try:
            for index, (video_url, view_count) in enumerate(filtered_video_urls, start=1):
                self.append_log(
                    f"[{index}/{len(filtered_video_urls)}] {self.downloader.format_view_count(view_count)} | {video_url}"
                )
                self.downloader.download_video_with_fallback(video_url)
        finally:
            self.downloader.download_dir = previous_dir
            self.downloader.set_entry_value(self.downloader.download_dir_entry, previous_dir)

        self.append_log("Hoan tat tim va tai video theo chu de.")

    def start_search_download(self):
        threading.Thread(target=self.search_and_download, daemon=True).start()
