import os
import threading
import time
from tkinter import filedialog

import customtkinter as ctk
import requests

from .helpers import append_textbox

MIN_VIEW_COUNT = 200_000
AI_KEYWORDS = [
    " ai ",
    "#ai",
    "artificial intelligence",
    "chatgpt",
    "midjourney",
    "stable diffusion",
    "runway",
    "sora",
    "kling",
    "veo",
    "pixverse",
    "pika",
    "generated by ai",
    "ai generated",
    "ai video",
    "ai voice",
    "ai cover",
    "ai animation",
    "ai art",
    "deepfake",
    "synthetic voice",
]


class SearchDownloadTab:
    def __init__(self, app, parent, downloader):
        self.app = app
        self.parent = parent
        self.downloader = downloader
        self.output_dir = os.getcwd()

        self._build_ui()
        self.append_log(f"Thu muc luu mac dinh: {self.output_dir}")

    def _build_ui(self):
        title = ctk.CTkLabel(
            self.parent,
            text="Tim chu de va tai video TikTok",
            font=ctk.CTkFont(size=18, weight="bold"),
        )
        title.pack(pady=(16, 10))

        note = ctk.CTkLabel(
            self.parent,
            text="Nhap chu de can tim, so video can tai va view toi thieu. Tool se tim video qua API, loc theo view va thoi luong roi tai ve.",
            wraplength=820,
            justify="left",
        )
        note.pack(padx=20, pady=(0, 10), anchor="w")

        keyword_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        keyword_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(keyword_frame, text="Chu de", width=120, anchor="w").pack(side="left")
        self.keyword_entry = ctk.CTkEntry(
            keyword_frame,
            width=620,
            placeholder_text="Vi du: dog play with ball",
        )
        self.keyword_entry.pack(side="left", padx=(0, 10), fill="x", expand=True)

        count_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        count_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(count_frame, text="So video", width=120, anchor="w").pack(side="left")
        self.limit_entry = ctk.CTkEntry(count_frame, width=120)
        self.limit_entry.pack(side="left")
        self.limit_entry.insert(0, "10")

        min_view_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        min_view_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(min_view_frame, text="Min view", width=120, anchor="w").pack(side="left")
        self.min_view_entry = ctk.CTkEntry(min_view_frame, width=120)
        self.min_view_entry.pack(side="left")
        self.min_view_entry.insert(0, str(MIN_VIEW_COUNT))

        max_duration_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        max_duration_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(max_duration_frame, text="Max giay", width=120, anchor="w").pack(side="left")
        self.max_duration_entry = ctk.CTkEntry(max_duration_frame, width=120)
        self.max_duration_entry.pack(side="left")
        self.max_duration_entry.insert(0, "0")
        ctk.CTkLabel(
            max_duration_frame, text="Chi tai video ngan hon so giay nay (0 = khong gioi han)", anchor="w"
        ).pack(side="left", padx=(10, 0))

        output_frame = ctk.CTkFrame(self.parent, fg_color="transparent")
        output_frame.pack(fill="x", padx=20, pady=6)
        ctk.CTkLabel(output_frame, text="Thu muc dich", width=120, anchor="w").pack(side="left")
        self.output_entry = ctk.CTkEntry(output_frame, width=620)
        self.output_entry.pack(side="left", padx=(0, 10), fill="x", expand=True)
        self.output_entry.insert(0, self.output_dir)
        ctk.CTkButton(output_frame, text="Chon dich", command=self.choose_output_dir, width=120).pack(side="left")

        ctk.CTkButton(self.parent, text="Tim va tai", command=self.start_search_download, width=180).pack(pady=8)

        self.log_box = ctk.CTkTextbox(self.parent, height=360, width=860)
        self.log_box.pack(padx=20, pady=(10, 20), fill="both", expand=True)

    def append_log(self, text):
        append_textbox(self.app, self.log_box, text)

    def set_entry_value(self, entry, value):
        entry.delete(0, "end")
        entry.insert(0, value)

    def choose_output_dir(self):
        selected = filedialog.askdirectory(initialdir=self.output_dir)
        if selected:
            self.output_dir = selected
            self.set_entry_value(self.output_entry, selected)
            self.append_log(f"Thu muc dich: {selected}")

    def get_search_label(self, keyword_or_url):
        return keyword_or_url.strip()

    def normalize_tikwm_video(self, video):
        video_id = video.get("video_id")
        author = video.get("author") or {}
        unique_id = author.get("unique_id")
        if not video_id or not unique_id:
            return None
        return {
            "id": video_id,
            "url": f"https://www.tiktok.com/@{unique_id}/video/{video_id}",
            "title": video.get("title") or "",
            "view_count": self.downloader.parse_count_value(video.get("play_count")),
            "duration": self.downloader.parse_count_value(video.get("duration")),
            "uploader": author.get("nickname") or "",
            "channel": unique_id,
        }

    def search_and_filter_videos(
        self, keyword, min_view_count, target_count, max_duration_seconds=0, max_candidates=200
    ):
        filtered_items = []
        seen_ids = set()
        cursor = 0
        scanned_count = 0

        while len(filtered_items) < target_count and scanned_count < max_candidates:
            response = requests.get(
                "https://www.tikwm.com/api/feed/search",
                params={"keywords": keyword, "count": 30, "cursor": cursor},
                headers={"accept": "application/json"},
                timeout=60,
            )
            response.raise_for_status()
            payload = response.json()
            if payload.get("code") != 0:
                raise RuntimeError(payload.get("msg") or "tikwm khong tra ve ket qua tim kiem.")

            data = payload.get("data") or {}
            raw_videos = data.get("videos") or []
            if not raw_videos:
                break

            for raw_video in raw_videos:
                video = self.normalize_tikwm_video(raw_video)
                if not video or video["id"] in seen_ids:
                    continue
                seen_ids.add(video["id"])
                scanned_count += 1

                if self.video_passes_filters(video, scanned_count, min_view_count, max_duration_seconds):
                    filtered_items.append((video["url"], video["view_count"]))
                    if len(filtered_items) >= target_count:
                        break
                if scanned_count >= max_candidates:
                    break

            if len(filtered_items) >= target_count or scanned_count >= max_candidates:
                break
            if not data.get("hasMore"):
                break
            cursor = data.get("cursor") or 0
            time.sleep(1)  # tikwm free gioi han ~1 request/giay

        return filtered_items, scanned_count

    def is_ai_content(self, info):
        combined_parts = [
            info.get("title", ""),
            info.get("description", ""),
            info.get("uploader", ""),
            info.get("channel", ""),
            " ".join(info.get("tags") or []),
        ]
        combined_text = f" {' '.join(part for part in combined_parts if part)} ".lower()
        return any(keyword in combined_text for keyword in AI_KEYWORDS)

    def video_passes_filters(self, video, index, min_view_count, max_duration_seconds):
        video_url = video["url"]
        view_count = video["view_count"]
        duration = video["duration"]

        if self.is_ai_content(video):
            self.append_log(f"[{index}] Bo qua vi nghi la noi dung AI | {video_url}")
            return False
        if max_duration_seconds > 0 and duration >= max_duration_seconds:
            self.append_log(
                f"[{index}] Bo qua vi dai {duration}s (can < {max_duration_seconds}s) | {video_url}"
            )
            return False
        if view_count < min_view_count:
            self.append_log(
                f"[{index}] Bo qua vi view thap: {self.downloader.format_view_count(view_count)} | {video_url}"
            )
            return False

        self.append_log(
            f"[{index}] Dat view: {self.downloader.format_view_count(view_count)} | {duration}s | {video_url}"
        )
        return True

    def search_and_download(self):
        keyword = self.keyword_entry.get().strip()
        self.output_dir = self.output_entry.get().strip() or self.output_dir

        if not keyword:
            self.append_log("Vui long nhap chu de can tim.")
            return

        try:
            limit = int(self.limit_entry.get().strip() or "6")
        except ValueError:
            self.append_log("So luong video phai la so.")
            return

        try:
            min_view_count = int(self.min_view_entry.get().strip() or str(MIN_VIEW_COUNT))
        except ValueError:
            self.append_log("Min view phai la so.")
            return

        try:
            max_duration_seconds = int(self.max_duration_entry.get().strip() or "0")
        except ValueError:
            self.append_log("Max giay phai la so.")
            return

        if max_duration_seconds < 0:
            self.append_log("Max giay phai >= 0.")
            return

        if limit <= 0:
            self.append_log("So luong video phai lon hon 0.")
            return

        if min_view_count < 0:
            self.append_log("Min view phai >= 0.")
            return

        if not self.output_dir:
            self.append_log("Vui long chon thu muc dich.")
            return

        os.makedirs(self.output_dir, exist_ok=True)

        duration_label = f" | max giay: {max_duration_seconds}" if max_duration_seconds > 0 else ""
        self.append_log(
            f"Dang tim video cho chu de: {self.get_search_label(keyword)} | so luong: {limit} | min view: {min_view_count}{duration_label}"
        )
        try:
            filtered_video_urls, scanned_count = self.search_and_filter_videos(
                keyword, min_view_count, limit, max_duration_seconds
            )
        except Exception as exc:
            self.append_log(f"Loi khi lay ket qua tim kiem: {exc}")
            return

        if scanned_count == 0:
            self.append_log("Khong tim thay video nao cho chu de nay.")
            return

        self.append_log(f"Da quet {scanned_count} video ung vien.")
        if not filtered_video_urls:
            self.append_log(f"Khong co video nao dat nguong >= {min_view_count} view.")
            return

        if len(filtered_video_urls) < limit:
            self.append_log(
                f"Chi tim duoc {len(filtered_video_urls)}/{limit} video dat nguong >= {min_view_count} view."
            )
        else:
            self.append_log(
                f"Tim thay du {len(filtered_video_urls)} video dat nguong >= {min_view_count} view."
            )
        previous_dir = self.downloader.download_dir
        self.downloader.download_dir = self.output_dir
        self.downloader.set_entry_value(self.downloader.download_dir_entry, self.output_dir)

        try:
            for index, (video_url, view_count) in enumerate(filtered_video_urls, start=1):
                self.append_log(
                    f"[{index}/{len(filtered_video_urls)}] {self.downloader.format_view_count(view_count)} | {video_url}"
                )
                self.downloader.download_video_with_fallback(video_url)
        finally:
            self.downloader.download_dir = previous_dir
            self.downloader.set_entry_value(self.downloader.download_dir_entry, previous_dir)

        self.append_log("Hoan tat tim va tai video theo chu de.")

    def start_search_download(self):
        threading.Thread(target=self.search_and_download, daemon=True).start()
